### ISSUE TITLE
workplan

### ISSUE THREAD

**Issue by nivertech** [nivertech/bezeq_line#1]
- [ ] call bezeq and get fax
- [ ] document the problem
- [ ] get apt owners ID (from home committee or Tabu)
- [ ] go to court
    - [ ] construction/fix cost + 
    - [ ] time without phone and internet connection +
    - [ ] cellcom modem data cost
